### ISSUE TITLE
Small leftover areas not being converted to new biome

### ISSUE THREAD

**Issue by Darkhand81** [Cube-Nation/BiomeEdit#2]
Hi!

When selecting a large biome, sometimes there are single leftover square areas that do not convert to the new biome.  Trying to set these spots manually also does not work; they remain locked as the old biome.

Screenshots:

http://i.imgur.com/sw7YQ
<img>http://imgur.com/YGPsz<img>

Let me know if you need any more info!

**Comment by DerFlash** [comment]
Should be fixed in the 1.0
