### ISSUE TITLE
Server crashes when using "/biome info"

### ISSUE THREAD

**Issue by CosmicVoyager** [Cube-Nation/BiomeEdit#4]
When I use "/biome info", after it says "Calculating biome bounderies..." I get disconnected and the console is unresponsive.

CraftBukkit version git-Bukkit-1.2.5-R1.0-b2149jnks (MC: 1.2.5) (Implementing API version 1.2.5-R1.0)
BiomeEdit v0.4

**Comment by DerFlash** [comment]
That happens sometimes when the area is too big. With the 1.0 it should be much better now.
