### ISSUE TITLE
NPE on latest 1.3.1 dev builds of Bukkit

### ISSUE THREAD

**Issue by Bronski** [Cube-Nation/BiomeEdit#5]
/biomeedit set ocean ROUND 30

15:53:51 [SEVERE] Exception in thread "Thread-3410"
15:53:51 [SEVERE] java.lang.NoClassDefFoundError: net/minecraft/server/Packet50PreChunk
15:53:51 [SEVERE]       at me.derflash.plugins.cnbiomeedit.BiomeEditor.makeCylinderArea(BiomeEditor.java:118)
15:53:51 [SEVERE]       at me.derflash.plugins.cnbiomeedit.BiomeEditor.makeAndMarkCylinderBiome(BiomeEditor.java:247)
15:53:51 [SEVERE]       at me.derflash.plugins.cnbiomeedit.BiomeEditor.makeAndMarkCylinderBiome(BiomeEditor.java:243)
15:53:51 [SEVERE]       at me.derflash.plugins.cnbiomeedit.CNBiomeEdit$1.run(CNBiomeEdit.java:123)
15:53:51 [SEVERE]       at org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)
15:53:51 [SEVERE]       at java.lang.Thread.run(Unknown Source)
15:53:51 [SEVERE] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.Packet50PreChunk
15:53:51 [SEVERE]       at java.net.URLClassLoader$1.run(Unknown Source)
15:53:51 [SEVERE]       at java.net.URLClassLoader$1.run(Unknown Source)
15:53:51 [SEVERE]       at java.security.AccessController.doPrivileged(Native Method)
15:53:51 [SEVERE]       at java.net.URLClassLoader.findClass(Unknown Source)
15:53:51 [SEVERE]       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
15:53:51 [SEVERE]       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
15:53:51 [SEVERE]       at java.lang.ClassLoader.loadClass(Unknown Source)
15:53:51 [SEVERE]       at java.lang.ClassLoader.loadClass(Unknown Source)
15:53:51 [SEVERE]       ... 6 more

Versions: CB 2296 / BE 0.4

I tried using WE/WG too and that didn't seem to work.

Thanks.

**Comment by MrSqueak** [comment]
I was just wondering if there is any work being done here? My server utilizes the plugin heavily and I would like to see it kept alive.

**Comment by DerFlash** [comment]
This was a "try" back then to reload the chunk informations on the client without needing to disconnect. This is fixed in the 1.0. Thx!
