### ISSUE TITLE
MCPC+ 1.4.7 not working

### ISSUE THREAD

**Issue by Zyles** [Cube-Nation/BiomeEdit#8]
I wish I could get this plugin to work, looks awesome but on a legacy FTB Ultimate server it wont. Running MCPC+ 1.4.7.

https://bitbucket.org/OniBait/mcpc-plus

Error:

> biome list
> 15:46:23 [WARNING] Unexpected exception while parsing console command "biome list"
> org.bukkit.command.CommandException: Unhandled exception executing command 'biome' in plugin BiomeEdit v1.0.1
>     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
>     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
>     at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchCommand(CraftServer.java:549)
>     at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchServerCommand(CraftServer.java:535)
>     at ho.al(DedicatedServer.java:353)
>     at ho.r(DedicatedServer.java:310)
>     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:746)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633)
>     at fy.run(ThreadMinecraftServer.java:16)
> Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_4_R1.command.
> ColouredConsoleSender cannot be cast to org.bukkit.entity.Player
>     at me.derflash.plugins.cnbiomeedit.CNBiomeEdit.onCommand(CNBiomeEdit.java:114)
>     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
>     ... 8 more

**Comment by Zyles** [comment]
Ok that was for the console only. In game "seems" to work.

However doing /biome list and then doing for example "/biome brush FOREST 5" says No such biome. Also I tried "/biome brush "Birch Forest" 5" same problem.

And what is the command to use the Worldedit selection? I didn't find an example anywhere.

**Comment by twonky4** [comment]
You can use the BiomeEdit only in game. Console commands are not supported. You have to set the <mode> parameter: ROUND, SQUARE, REPLACE, WE, WG

e.g: /biome brush FOREST ROUND 5

For use Worldedit selection try mode "WE".
