### ISSUE TITLE
Plugin doesn't detecting WorldEdit and WorldGuard

### ISSUE THREAD

**Issue by Wolfyxon** [Cube-Nation/BiomeEdit#9]
I have installed WolrdEdit and WorldGuard but plugin says: You need to instal WolrdEdit plugin

**Comment by d1rty-pixel** [comment]
This plugin is not maintained anymore. You may want to look for other plugins like BiomeControl (tested against spigot api 1.14.4). I believe that worldedit has biome editing features, but that should better be requested/asked at their support channel (they use discord btw).

Sorry.
